services:
  influxdb:
    container_name: caviar.influxdb
    image: influxdb:latest
    restart: unless-stopped
    ports:
      - '8086:8086'
    env_file:
      - system.env
    networks:
      demo:
        ipv4_address: 192.168.10.13
  
  influxdb_cli:
    container_name: caviar.influxdb_cli
    links:
      - influxdb
    image: influxdb:latest
    volumes: 
      - ./monitor/templates:/home/templates:rw
    entrypoint: influx apply -o "lasse" -f /home/templates/template1.yml -t "nlUwG8uHneAP2SVYWRqOk0OJ1p19H8ddKR9o292rEmk2ZMli33cO8WqndkM1IWgrNqbGmI7tia1X4AGb6PXWQQ==" --host=http://influxdb:8086 --force yes
    restart: on-failure:20
    depends_on:
      - influxdb
    networks:
      demo:
        ipv4_address: 192.168.10.14

  grafana:
    image: grafana/grafana-oss
    container_name: caviar.grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    user: "0"
    privileged: true
    volumes:
      - ./monitor/grafana/grafana.db:/var/lib/grafana/grafana.db
      - ./monitor/grafana/plugins:/var/lib/grafana/plugins
      #- ./monitor/grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - influxdb
    networks:
      demo:
        ipv4_address: 192.168.10.16
networks:
  demo:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
