task: train

defaults:
  - validation: ../validation

epoch: 500

data:
  batch_size: 16
  image_size: ${image_size}
  cpu_num: ${cpu_num}
  shuffle: True
  pin_memory: True
  data_augment:
    Mosaic: 1
    # MixUp: 1
    # HorizontalFlip: 0.5
    RandomCrop: 1
    RemoveOutliers: 1e-8

optimizer:
  type: SGD
  args:
    lr: 0.01
    weight_decay: 0.0005
    momentum: 0.937
    nesterov: true

loss:
  objective:
    BCELoss: 0.5
    BoxLoss: 7.5
    DFLoss: 1.5
  aux:
    0.25
  matcher:
    iou: CIoU
    topk: 10
    factor:
      iou: 6.0
      cls: 0.5

scheduler:
  type: LinearLR
  warmup:
    epochs: 3.0
  args:
    total_iters: ${task.epoch}
    start_factor: 1
    end_factor: 0.01

ema:
  enable: true
  decay: 0.995
