name: pre-commit
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
      - run: bash Miniconda3-latest-Linux-x86_64.sh -b -u
      - run: conda env create -f env.yml
      - run: conda run -n env pre-commit install
      - run: pipenv run -n env pre-commit run --all-files
