name: pre-commit
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - run: $CONDA/bin/conda env create -f env.yml
      - run: $CONDA/bin/conda run -n env pre-commit install
      - run: $CONDA/bin/conda run -n env pre-commit run --all-files
